export const ErrorRVIA = {
    600: "Error en número de argumentos",
    601: "Argumentos inválidos",
    602: "NO SE PUDO ABRIR EL ARCHIVO PARA LEER EL TOKEN",
    603: "NO SE PUDO ABRIR EL ARCHIVO CHECKMARX" ,
    604: "Error en número de argumentos [getTotalFiles]",
    605: "Argumentos inválidos (getTotalFiles)",
    606: "Error: system call failed. (getTotalFiles)",
    607: "Command failed with exit status",
    608: "Command did not terminate normally.",
    609: "ERROR: El archivo de totales está vacío.",
    610: "Error: system call failed. (getTotalCloc)",
    611: "Command failed with exit status (getTotalCloc)",
    612: "Command did not terminate normally (getTotalCloc).",
    613: "ERROR: El archivo de totales está vacío (getTotalCloc).",
    614: "Error: Incorrect employee number.. (getTotalCloc)",
    615: "Error: No se pudo registrar el control del proyecto.",
    616: "Error: No se pudo registrar el lenguaje",
    617: "Error en número de argumentos [validateTBEmployeeExists]",
    618: "Argumentos inválidos [validateTBEmployeeExists]",
    619: "No se pudo abrir el archivo para leer el token.",
    620: "El token proporcionado no coincide con el token guardado.",
    621: "El token ha expirado.",
    622: "Error en número de argumentos (initEncryptDecryptRvia)",
    623: "Argumentos inválidos (initEncryptDecryptRvia)",
    624: "Tipo de archivo incorrecto (initEncryptDecryptRvia)",
    625: "Error: system call failed. [processFile]",
    626: "Error: system call failed. [processFileWithCheckmarx]",
    627: "Error: system call failed. [processFileByReinforcement]",
    628: "Error en número de argumentos [getTotalDataFromCheckmarx]",
    629: "Argumentos inválidos [getTotalDataFromCheckmarx]",
    630: "Error en número de argumentos [createOverviewDoc]",
    631: "Argumentos inválidos [createOverviewDoc]",
    632: "Error al cambiar de directorio [createOverviewDoc]",
    633: "Error al ejecutar el script. [createOverviewDoc]",
    634: "Error al comprimir el directorio [createOverviewDoc].",
    635: "Error al cambiar al directorio origen [createOverviewDoc].",
    636: "El directorio no existe o no es un directorio: [deleteDirectory]",
    637: "Error al abrir archivo [saveLatestRecordsDocumentationBito]",
    638: "",
    639: "",
    640: "",
    666: "El empleado no está registrado"
}